### ISSUE TITLE
Add a entry to one of the available categories

### ISSUE THREAD

**Issue by martink-rsa** [Noroff-FEU-Hackathons/student-resources#8]
## Task:

Create a new entry for one of the categories seen in the main README.md: https://github.com/Noroff-FEU-Hackathons/student-resources

## Acceptance Criteria:

- [ ] Create a new entry to one of the categories. An entry must include:
  - [ ] An H3 heading `###` that should be numbered correctly according to where the item is in the list e.g `### 1. Basic Example:`;
  - [ ] A link that follows after the title on its own line;
  - [ ] A description of the site/article and why its helpful.
- [ ] If there are already entries for that category then add it to the bottom of list of entries.
- [ ] If the category you have chosen only has the example entry, then replace this example entry with your own entry. 

## More Info:

NOTE: Make sure to have a look at the CONTRIBUTING.md file for guidance on how to open a PR: https://github.com/Noroff-FEU-Hackathons/student-resources/blob/master/CONTRIBUTING.md

**Comment by pnbakken** [comment]
I wouldn't mind doing one more if that's possible

**Comment by martink-rsa** [comment]
Assigned to you
